"""INFRA-06 checkin scored queue flag

Revision ID: 15dc6e10375a
Revises: 1aeee1926316
Create Date: 2026-07-22 10:40:32.045040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15dc6e10375a'
down_revision: Union[str, None] = '1aeee1926316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_ins', sa.Column('scored', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_ins', 'scored')
    # ### end Alembic commands ###
