"""INFRA-05 notification attempts column

Revision ID: 1aeee1926316
Revises: 8ab7f8057e0a
Create Date: 2026-07-22 10:34:31.093966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aeee1926316'
down_revision: Union[str, None] = '8ab7f8057e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('attempts', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'attempts')
    # ### end Alembic commands ###
