"""INFRA-02 remaining domain entities

Revision ID: 8ab7f8057e0a
Revises: a80c0d231744
Create Date: 2026-07-22 10:22:35.028745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ab7f8057e0a'
down_revision: Union[str, None] = 'a80c0d231744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Enum('seed', 'school', name='activity_scope'), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('breathing', 'grounding', 'stretch', 'brain_break', name='activity_type'), nullable=False),
    sa.Column('age_band', sa.Enum('b5_7', 'b8_11', 'b12_18', 'all', name='activity_age_band'), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_recipient_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('recipient_staff_ids', postgresql.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_recipient_configs_school_id'), 'alert_recipient_configs', ['school_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    op.create_table('calendar_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('holidays', postgresql.ARRAY(sa.Date()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_configs_school_id'), 'calendar_configs', ['school_id'], unique=False)
    op.create_table('class_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_groups_school_id'), 'class_groups', ['school_id'], unique=False)
    op.create_table('concern_word_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('words', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'premium', name='subscription_tier'), nullable=False),
    sa.Column('state', sa.Enum('trial', 'active', 'free', 'cancelled', name='subscription_state'), nullable=False),
    sa.Column('trial_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_extension_count', sa.SmallInteger(), nullable=False),
    sa.Column('term_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_school_id'), 'subscriptions', ['school_id'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('mood_value', sa.SmallInteger(), nullable=False),
    sa.Column('reflection_text', sa.Text(), nullable=True),
    sa.Column('captured_offline', sa.Boolean(), nullable=False),
    sa.Column('within_window', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_school_id'), 'check_ins', ['school_id'], unique=False)
    op.create_index(op.f('ix_check_ins_student_id'), 'check_ins', ['student_id'], unique=False)
    op.create_index('ix_checkins_school_submitted', 'check_ins', ['school_id', 'submitted_at'], unique=False)
    op.create_table('class_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_class_student')
    )
    op.create_index(op.f('ix_class_memberships_class_id'), 'class_memberships', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_memberships_student_id'), 'class_memberships', ['student_id'], unique=False)
    op.create_table('data_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('export', 'export_and_delete', name='data_export_kind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'completed', name='data_export_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['staff_accounts.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_exports_school_id'), 'data_exports', ['school_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'sent', 'accepted', 'revoked', 'expired', name='invitation_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['staff_accounts.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invitations_school_id'), 'invitations', ['school_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel', sa.Enum('email', 'in_app', name='alert_channel'), nullable=False),
    sa.Column('delivery_status', sa.Enum('queued', 'sent', 'delivered', 'failed', 'retrying', name='delivery_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['staff_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('parental_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', name='parental_consent_status'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parental_consents_student_id'), 'parental_consents', ['student_id'], unique=False)
    op.create_table('staff_class_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Enum('owner', 'shared', name='staff_class_scope'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'class_id', name='uq_staff_class')
    )
    op.create_index(op.f('ix_staff_class_access_class_id'), 'staff_class_access', ['class_id'], unique=False)
    op.create_index(op.f('ix_staff_class_access_staff_id'), 'staff_class_access', ['staff_id'], unique=False)
    op.create_table('activity_engagements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('checkin_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('offered', 'started', 'completed', name='activity_engagement_status'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['checkin_id'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_engagements_student_id'), 'activity_engagements', ['student_id'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('checkin_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('concern_word', 'slow_burn', name='flag_type'), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('band', sa.Enum('immediate', 'triage', 'none', name='flag_band'), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'escalated', 'actioned', 'closed', name='flag_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_school_id'), 'flags', ['school_id'], unique=False)
    op.create_index('ix_flags_school_status', 'flags', ['school_id', 'status'], unique=False)
    op.create_index(op.f('ix_flags_student_id'), 'flags', ['student_id'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flag_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'in_app', name='alert_channel'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'failed', 'retrying', name='delivery_status'), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['staff_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_flag_id'), 'alert_deliveries', ['flag_id'], unique=False)
    op.create_table('flag_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flag_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('alerted', 'viewed', 'acted', 'escalated', name='flag_event_type'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['staff_accounts.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flag_events_flag_id'), 'flag_events', ['flag_id'], unique=False)
    op.create_table('supportive_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('flag_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['staff_accounts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportive_notes_student_id'), 'supportive_notes', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supportive_notes_student_id'), table_name='supportive_notes')
    op.drop_table('supportive_notes')
    op.drop_index(op.f('ix_flag_events_flag_id'), table_name='flag_events')
    op.drop_table('flag_events')
    op.drop_index(op.f('ix_alert_deliveries_flag_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index(op.f('ix_flags_student_id'), table_name='flags')
    op.drop_index('ix_flags_school_status', table_name='flags')
    op.drop_index(op.f('ix_flags_school_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_activity_engagements_student_id'), table_name='activity_engagements')
    op.drop_table('activity_engagements')
    op.drop_index(op.f('ix_staff_class_access_staff_id'), table_name='staff_class_access')
    op.drop_index(op.f('ix_staff_class_access_class_id'), table_name='staff_class_access')
    op.drop_table('staff_class_access')
    op.drop_index(op.f('ix_parental_consents_student_id'), table_name='parental_consents')
    op.drop_table('parental_consents')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_invitations_school_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_data_exports_school_id'), table_name='data_exports')
    op.drop_table('data_exports')
    op.drop_index(op.f('ix_class_memberships_student_id'), table_name='class_memberships')
    op.drop_index(op.f('ix_class_memberships_class_id'), table_name='class_memberships')
    op.drop_table('class_memberships')
    op.drop_index('ix_checkins_school_submitted', table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_student_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_school_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_subscriptions_school_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('concern_word_lists')
    op.drop_index(op.f('ix_class_groups_school_id'), table_name='class_groups')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_calendar_configs_school_id'), table_name='calendar_configs')
    op.drop_table('calendar_configs')
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alert_recipient_configs_school_id'), table_name='alert_recipient_configs')
    op.drop_table('alert_recipient_configs')
    op.drop_table('activities')
    # ### end Alembic commands ###
