"""INFRA-01 identity + auth-infra tables

Revision ID: a80c0d231744
Revises: 
Create Date: 2026-07-21 20:51:54.767816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80c0d231744'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_at'), 'login_attempts', ['at'], unique=False)
    op.create_index(op.f('ix_login_attempts_identifier'), 'login_attempts', ['identifier'], unique=False)
    op.create_table('mfa_otps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_otps_subject_id'), 'mfa_otps', ['subject_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_staff_id'), 'password_reset_tokens', ['staff_id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'rejected', name='school_status'), nullable=False),
    sa.Column('tier', sa.Enum('free', 'premium', name='school_tier'), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('sign_in_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sign_in_code')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('staff', 'student', 'admin', name='session_kind'), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('mfa_pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_subject_id'), 'sessions', ['subject_id'], unique=False)
    op.create_table('staff_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('sso_subject', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.Enum('password', 'google', 'microsoft', name='auth_provider'), nullable=False),
    sa.Column('role', sa.Enum('teacher', 'support', 'leadership', 'district', name='staff_role'), nullable=False),
    sa.Column('status', sa.Enum('invited', 'sent', 'accepted', 'active', 'deactivated', name='staff_status'), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'email', name='uq_staff_school_email')
    )
    op.create_index(op.f('ix_staff_accounts_school_id'), 'staff_accounts', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_accounts_sso_subject'), 'staff_accounts', ['sso_subject'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('age_band', sa.Enum('b5_7', 'b8_11', 'b12_18', name='student_age_band'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='student_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_staff_accounts_sso_subject'), table_name='staff_accounts')
    op.drop_index(op.f('ix_staff_accounts_school_id'), table_name='staff_accounts')
    op.drop_table('staff_accounts')
    op.drop_index(op.f('ix_sessions_subject_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('schools')
    op.drop_index(op.f('ix_password_reset_tokens_staff_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_mfa_otps_subject_id'), table_name='mfa_otps')
    op.drop_table('mfa_otps')
    op.drop_index(op.f('ix_login_attempts_identifier'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('internal_admins')
    # ### end Alembic commands ###
